---
title: "Data validation for July 2017 between OpenJobs and Burning Glass"
author: "Eirik Iversen"
date: "4/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo= FALSE, include = FALSE}
library(data.table)
library(sf)
library(dplyr)
library(stringr)
library(lubridate)
library(leaflet)
```


### Import datasets
```{r}
BG_join_point <- readRDS('../../data/stem_edu/working/BGexplorevalidate/BG_Shapefiles/BG_join_point.RDS')
OJ_join_point <- readRDS('../../data/stem_edu/working/BGexplorevalidate/BG_Shapefiles/open_point.RDS')
econ_va_counties <- readRDS("../../data/stem_edu/working/BGexplorevalidate/econvacounties.RDS")
```

### Open Job Economic region job aggregates
```{r, echo = FALSE}
OJ_join_point$occfam <- str_extract(OJ_join_point$normalizedTitle_onetCode, "[0-9]{2}")
joined <- st_join(OJ_join_point, econ_va_counties)

#filter out the correct dates
joined <- filter(joined,as.Date(joined$datePosted) >= "2017-07-01")

#
joined_within <- joined %>% filter(within == TRUE) # removes 101 observations

# aggregate jobs per county
#join_cty_ct <- joined_within %>% group_by(fipscounty) %>% summarise(count = n())
join_ecoreg_ct <- joined_within %>% group_by(GOorg) %>% summarise(count = n())
econ_va_counties$COUNTYFP <- as.integer(econ_va_counties$COUNTYFP)
join_ecoreg_ct <- st_join(econ_va_counties, join_ecoreg_ct, suffix = c("NAME" = "NAME"))

labels <- sprintf(
  "<strong>%s</strong><br/>%s<br/>%s",
  join_ecoreg_ct$count, join_ecoreg_ct$NAMELSAD, join_ecoreg_ct$GOorgNAME
) %>% lapply(htmltools::HTML)

leaflet(join_ecoreg_ct) %>% addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              fillColor = ~colorQuantile("YlOrRd", count)(count),
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"))
```

### Burning Glass Economic region job aggregates
```{r, echo = FALSE}
#make sure this reads in BG instead of openjobs
join_ecoreg_ct <- BG_join_point %>% group_by(GOorg) %>% summarise(count = n())

#code copied from above chunk
join_ecoreg_ct <- st_join(econ_va_counties, join_ecoreg_ct, suffix = c("NAME" = "NAME"))
labels <- sprintf(
  "<strong>%s</strong><br/>%s<br/>%s",
  join_ecoreg_ct$count, join_ecoreg_ct$NAMELSAD, join_ecoreg_ct$GOorgNAME
) %>% lapply(htmltools::HTML)

leaflet(join_ecoreg_ct) %>% addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              fillColor = ~colorQuantile("YlOrRd", count)(count),
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"))
```

### Comparison of Jobs and occfam in Economic Regions
```{r, echo= FALSE}
OJ_join_point$occfam <- str_extract(OJ_join_point$normalizedTitle_onetCode, "[0-9]{2}")

#filter out the correct dates
joined <- filter(OJ_join_point,as.Date(OJ_join_point$datePosted) >= "2017-07-01")
joined <- st_join(joined, econ_va_counties)

#
joined_within <- joined %>% filter(within == TRUE) # removes 101 observations

# aggregate jobs per county
#join_cty_ct <- joined_within %>% group_by(fipscounty) %>% summarise(count = n())
OJ_job <- joined_within %>% group_by(GOorg) %>% summarise(count = n())
BG_job <- BG_join_point %>% group_by(GOorg) %>% summarise(count = n())
#clean up
st_geometry(OJ_job) <- NULL
st_geometry(BG_job) <- NULL
BG_job <- BG_job[complete.cases(BG_job$GOorg),]

jobtable <- left_join(OJ_job,BG_job, by='GOorg')
colnames(jobtable) <- c("GOorg", "Open Jobs Count", "Burning Glass Count") 
knitr::kable(jobtable)


OJ_occ <- joined_within %>% group_by(GOorg,occfam) %>% summarise(count = n())
BG_occ <- BG_join_point %>% group_by(GOorg,occfam) %>% summarise(count = n())
#clean up
st_geometry(OJ_occ) <- NULL
st_geometry(BG_occ) <- NULL
OJ_occ <- OJ_occ[complete.cases(OJ_occ$occfam),]
OJ_occ <- OJ_occ[OJ_occ$occfam != '99',]
BG_occ <- BG_occ[complete.cases(BG_occ$GOorg),]
BG_occ <- BG_occ[BG_occ$occfam != 'na',]

occtable <- left_join(OJ_occ,BG_occ, by=c('GOorg', 'occfam'))
colnames(occtable) <- c("GOorg", "occfam","Open Jobs OCC Count", "Burning Glass OCC Count") 
knitr::kable(occtable)


```


